// orli/src/components/App.tsx
import React from "react";
import "./App.css";
import { CElementService } from "../services/celement.service";
import * as PIXI from "pixi.js";
import { Ioc } from "../base/inversify.config";

import { CElementPropertiesComponent } from "./celement-properties/celement-properties.component";
import { CElementAddNewComponent } from "./celement-add-new/celement-add-new.component";
import { currentSelectedCelementSelector } from "../features/ui-editor/celement/celement.selectors";
import store from "../rx/store";
import { watch } from "../rx/watch";

export class App extends React.Component<{}, {}> {
  private readonly _cElementService: CElementService;

  private isEditorCreated = false;

  constructor(props: any) {
    super(props);

    const iocContainer = Ioc.Conatiner;
    this._cElementService = iocContainer.get<CElementService>(CElementService);

    // this.state = new State();
  }

  render() {
    return (
      <div id="app-wrapper">
        <CElementAddNewComponent />

        <div id="editor-wrapper"></div>

        <CElementPropertiesComponent />
      </div>
    );
  }

  componentDidMount() {
    this.createEditor();
    this.bindEditorEvents();
  }

  private createEditor() {
    if (this.isEditorCreated) return;

    // The application will create a renderer using WebGL, if possible,
    // with a fallback to a canvas render. It will also setup the ticker
    // and the root stage PIXI.Container
    const app = new PIXI.Application({
      backgroundColor: 0xffffff,
      antialias: true,
    });
    const { renderer } = app;

    this._cElementService.initialize(new PIXI.InteractionManager(renderer));

    const rootEl = document.getElementById("editor-wrapper") as HTMLElement;
    // (renderer as Renderer).addSystem(<any>EventSystem, 'events');
    app.resizeTo = rootEl;

    renderer.render(app.stage);
    // The application will create a canvas element for you that you
    // can then insert into the DOM
    rootEl.appendChild(app.view);

    const container = this._cElementService.createCElement(
      0,
      0,
      400,
      400,
      0x99aaaa
    );

    const cel1 = this._cElementService.createCElement(0, 20, 60, 30, 0x66ccff);
    cel1.graphics.x = container.graphics.x;
    // cel1.graphics.rotation = 0.5;
    container.addChild(cel1);

    const cel2 = this._cElementService.createCElement(0, 50, 60, 30, 0x66ccff);
    cel2.graphics.x = container.graphics.x;
    container.addChild(cel2);

    app.stage.addChild(container.graphics);

    this.isEditorCreated = true;
  }

  private bindEditorEvents() {
    let wSelectedCel = watch(() =>
      currentSelectedCelementSelector(store.getState().editor)
    );
    store.subscribe(
      wSelectedCel((newId, oldId) => {
        if (oldId) {
          const cel = this._cElementService.getCElement(oldId)!;
          cel.isSelected = false;
        }

        if (!newId) return;

        const cel = this._cElementService.getCElement(newId)!;
        cel.isSelected = true;
      })
    );
  }
}

// src/app/app.component.ts
import { AfterViewInit, Component, ElementRef, ViewChild } from '@angular/core';
import * as PIXI from 'pixi.js';
import { CElementService } from 'src/services/celement.service';

@Component({
  selector: 'orli-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss'],
})
export class AppComponent implements AfterViewInit {
  @ViewChild('rootView') rootView!: ElementRef;

  constructor(private readonly _cElementService: CElementService) {}

  ngAfterViewInit(): void {
    // The application will create a renderer using WebGL, if possible,
    // with a fallback to a canvas render. It will also setup the ticker
    // and the root stage PIXI.Container
    const app = new PIXI.Application({ backgroundColor: 0xffffff });

    const { renderer } = app;
    // (renderer as Renderer).addSystem(<any>EventSystem, 'events');
    app.resizeTo = this.rootView.nativeElement;

    renderer.render(app.stage);
    // The application will create a canvas element for you that you
    // can then insert into the DOM
    this.rootView.nativeElement.appendChild(app.view);

    const container = this._cElementService.createCElement(0, 0, 400, 400, 0x99aaaa);

    const cel1 = this._cElementService.createCElement(0, 20, 60, 30, 0x66ccff);
    cel1.graphics.x = container.graphics.x;
    container.addChild(cel1);

    const cel2 = this._cElementService.createCElement(0, 50, 60, 30, 0x66ccff);
    cel2.graphics.x = container.graphics.x;
    container.addChild(cel2);

    // const circle = container.graphics.drawCircle(0, 0, 10);
    // circle.beginFill(0x66ccff);
    // circle.endFill();
    // container.graphics.addChild(circle);

    app.stage.addChild(container.graphics);
  }

  example(app: PIXI.Application) {
    // load the texture we need
    app.loader.add('bunny', 'assets/bunny.png').load((loader, resources) => {
      // This creates a texture from a 'bunny.png' image
      const bunny = new PIXI.Sprite(resources['bunny'].texture);

      // Setup the position of the bunny
      bunny.x = app.renderer.width / 2;
      bunny.y = app.renderer.height / 2;

      // Rotate around the center
      bunny.anchor.x = 0.5;
      bunny.anchor.y = 0.5;

      // Add the bunny to the scene we are building
      app.stage.addChild(bunny);

      // Listen for frame updates
      app.ticker.add(() => {
        // each frame we spin the bunny around a bit
        bunny.rotation += 0.01;
      });
    });
  }
}

<div id="main-wrapper">
  <div id="root-view" #rootView></div>
  <div id="cel-properties-wrapper"></div>
</div>
